name: Debug Build

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Swift Debug Build
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (debug)
        run: swift build -c debug
